# Generated by Django 2.1.3 on 2018-11-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoDouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('职位', models.TextField(blank=True, null=True)),
                ('名称', models.TextField(blank=True, null=True)),
                ('地点', models.TextField(blank=True, null=True)),
                ('工资', models.TextField(blank=True, null=True)),
                ('日期', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_double',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
