# Generated by Django 2.1.3 on 2018-12-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextM', '0002_auto_20181127_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangodouble',
            options={},
        ),
    ]
